### ISSUE TITLE
Migration files are not sorted out properly based on timestamp before migrating

### ISSUE THREAD

**Issue by kuiamenhmartin** [Arjorie/loopback-mongodb-migrate#1]
I encountered this issue when creating migration files with a different year timestamp. When I started running the migration, it first migrated the newly created migration files and then the old ones so the data migrated became unreliable.

**Comment by arjorie** [comment]
Hi @kuiamenhmartin I already fixed this issue, please update the library in your project and try again. Let me know if there are any other issues. Cheers!
